#!/usr/bin/env bash
set -e

echo ""
echo "FREE AI STUDIO — CONFIGURATION DÉBUTANT"
echo "======================================="
echo ""
echo "Commencez simplement avec Gemini, Groq et OpenRouter."
echo "Les autres services sont optionnels."
echo ""
echo "1) Gemini — chat, vision et secours gratuit"
echo "   Créer une clé : https://aistudio.google.com/apikey"
echo ""
echo "2) Groq — réponses rapides et transcription audio"
echo "   Créer une clé : https://console.groq.com/keys"
echo ""
echo "3) OpenRouter — plusieurs modèles gratuits + Boost optionnel"
echo "   Créer une clé : https://openrouter.ai/settings/keys"
echo ""
echo "OPTIONNELS"
echo "----------"
echo "Hugging Face : modèles ouverts (poids téléchargeables) et offres gratuites"
echo "  https://huggingface.co/settings/tokens"
echo ""
echo "Cloudflare Workers AI : fournisseur cloud de secours"
echo "  https://developers.cloudflare.com/workers-ai/get-started/rest-api/"
echo ""
echo "Modal : machine cloud puissante / GPU pour image et vidéo"
echo "  https://modal.com/docs/guide"
echo ""
echo "Kaggle : GPU gratuit via notebooks pour tâches lourdes"
echo "  https://www.kaggle.com/settings"
echo ""
echo "E2B : ordinateur temporaire isolé pour tester du code"
echo "  https://e2b.dev/"
echo ""
echo "Daytona : environnement séparé pour tester un projet ou du code"
echo "  https://www.daytona.io/"
echo ""
echo "Conseil : si vous débutez, ignorez les options ci-dessus."
echo ""
echo "Éditez ensuite .env uniquement si nécessaire, ou demandez à votre assistant VS Code de le faire."
