Write-Host ""
Write-Host "FREE AI STUDIO - CONFIGURATION DEBUTANT"
Write-Host "======================================="
Write-Host ""
Write-Host "Commencez simplement avec Gemini, Groq et OpenRouter."
Write-Host "Les autres services sont optionnels."
Write-Host ""
Write-Host "1) Gemini - chat, vision et secours gratuit"
Write-Host "   https://aistudio.google.com/apikey"
Write-Host ""
Write-Host "2) Groq - reponses rapides et transcription audio"
Write-Host "   https://console.groq.com/keys"
Write-Host ""
Write-Host "3) OpenRouter - plusieurs modeles gratuits + Boost optionnel"
Write-Host "   https://openrouter.ai/settings/keys"
Write-Host ""
Write-Host "OPTIONNELS"
Write-Host "Hugging Face : plus de modeles open source"
Write-Host "Cloudflare Workers AI : fournisseur cloud de secours"
Write-Host "Modal : machine cloud puissante / GPU pour image et video"
Write-Host "Kaggle : GPU gratuit via notebooks pour taches lourdes"
Write-Host "E2B : ordinateur temporaire isole pour tester du code"
Write-Host "Daytona : environnement separe pour tester code/projets"
Write-Host ""
Write-Host "Conseil : si vous debutez, ignorez ces options."
